env:
  global:
    - REPO="/Tangerine-Community/Tangerine/client"
    - CI_HOME=`pwd`/$REPO
language: node_js
node_js:
  - "node"
before_install:
  - echo TRAVIS_BUILD_DIR= ${TRAVIS_BUILD_DIR}
  - echo CI_HOME= ${CI_HOME}
  - cd $CI_HOME
  - npm install -g grunt-cli
install: npm install
before_script:
  - echo TRAVIS_BUILD_DIR= ${TRAVIS_BUILD_DIR}
  - echo CI_HOME= ${CI_HOME}
  - cd $CI_HOME
  - npm install -g bower
  - bower install
notifications:
  slack: rti:nBr3dvYD5mClKt1pAnuHgH8J
